---
"on":
  push:
  pull_request:
  workflow_dispatch:

jobs:

  system-python:
    strategy:
      matrix:
        os:
          - "ubuntu-24.04"
          - "macos-15"  # arm64
          - "macos-13"  # x86-64
          - "windows-2022"
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-python@v5.4.0
        with:
          python-version: "3.13"
      - name: Install uv
        run: |
          python -m pip install "uv == 0.5.26"
      - name: Install Nuitka
        run: |
          uv --no-progress venv
          uv --no-progress pip install "nuitka == 2.6.2"

      - name: uv run -m nuitka --version
        run: |
          uv --no-progress run --frozen --module -- nuitka --version

      - name: Build binary
        run: >
          uv --no-progress run --frozen --module -- nuitka
          --onefile --assume-yes-for-downloads --output-filename=my-cli-${{ matrix.os }}.bin
          my_cli/__main__.py

      - name: Set binary permissions
        if: runner.os != 'Windows'
        run: |
          chmod +x my-cli-${{ matrix.os }}.bin

      - name: Run binary
        run: |
          my-cli-${{ matrix.os }}.bin
